### ISSUE TITLE
Consider dropping your blacklist for a more inclusive one.

### ISSUE THREAD

**Issue by wormeyman** [adaprile/Gravity-Forms-WP-Comment-Blacklist#1]
https://github.com/splorp/wordpress-comment-blacklist

Just a thought but I like to use the above project for my Deny List as it is super inclusive and they are quick to fix false positives.

**Comment by adaprile** [comment]
Thank you for the suggestion! 

I actually already had the splorp list linked under the "**More Documentation**" section of my README.md. I have a personal reason for the primitive blacklist I included in my files, so I won't be removing it. Instead I made better note of the splorp list under "**How to Use**". Hopefully it is more helpful this way.

Thanks again!
