### ISSUE TITLE
This solution is not working with the latest gravity form version 2.5.x

### ISSUE THREAD

**Issue by 2h1n846** [adaprile/Gravity-Forms-WP-Comment-Blacklist#2]
Hey bro
Do you have some time to update this, please..
It was working great in the past. After updating gravity form to 2.5.x, it's work anymore...

**Comment by adaprile** [comment]
Hm, I took a look. I tested a brand new form built with the 2.5 builder and everything seems to be working for me. It does not seem Gravity Forms made any changes to the "gform_validation" hook. No PHP errors either. 

Now, GF definitely made changes to the markup, I am wondering, maybe there is a specific field that is somehow incompatible? What fields are in use on your form?

Also, what version of WP are you using? A few months back, I updated the code to accommodate a change in versions of WP greater than 5.5. Are you using the latest version of PHP code?

**Comment by 2h1n846** [comment]
It's just Textarea.
It was working great till the last month when the plugin got an update.
My plugin version: 2.5.5.1
PHP and wordpress are up to date.

**Comment by 2h1n846** [comment]
never mind
I have tested on different website and this worked

**Comment by ninecdev** [comment]
I never used this but today used as suggested by chatGPT and and I am using https://github.com/splorp/wordpress-comment-blacklist for my keys and your filter still block common words like "Josh", "Testing" etc.

Then I asked GPT to fix the issues and it came up with this, not sure if it's right or wrong but it seems to be working, @adaprile can you give it a look, thanks

`add_filter('gform_validation', 'custom_validation');
function custom_validation($validation_result) {
    // Retrieve the blacklist from WordPress options.
    if ( false === get_option( 'disallowed_keys' ) ) {
        $blacklisted = get_option('blacklist_keys'); // WP < 5.5
    } else {
        $blacklisted = get_option('disallowed_keys'); // WP >= 5.5
    }
    
    // Split on newline characters so that multi-word phrases and special characters are preserved.
    $badWords = preg_split("/\r\n|\r|\n/", $blacklisted);
    
    // Function to check if the field value contains any of the disallowed phrases.
    function contains($field_value, array $badWords) {
        foreach ($badWords as $badWord) {
            $badWord = trim($badWord);
            if (!$badWord) {
                continue; // Skip empty entries
            }
            // Use regex with word boundaries.
            // If your phrases include special characters that shouldn't be "word" limited,
            // you might consider omitting the \b tokens.
            $pattern = '/\b' . preg_quote($badWord, '/') . '\b/i';
            if (preg_match($pattern, $field_value)) {
                return true;
            }
        }
        return false;
    }
    
    $form = $validation_result['form'];
    foreach ($form['fields'] as &$field) {
        $field_value = rgpost("input_{$field['id']}");
        if (contains($field_value, $badWords)) {
            $validation_result['is_valid'] = false;
            $field->failed_validation = true;
            $field->validation_message = 'This field contains disallowed words!';
            break;
        }
    }
    
    $validation_result['form'] = $form;
    return $validation_result;
}`
